-- Adds a durable "Download survey PDF" for the boiler pre-installation
-- survey (0007_boiler_surveys.sql) — same idea as
-- `signature_requests.signed_pdf_path` (0010_self_signed_documents.sql).
--
-- Generated by `generateAndStoreSurveyPdf` (src/data/boiler-survey-service.ts),
-- called from `submitBoilerSurvey` (src/app/survey/[token]/actions.ts)
-- whenever the on-site surveyor submits/resubmits. Stored in the existing
-- `boiler-survey-photos` bucket at `${survey.id}/survey.pdf` — no new
-- bucket needed, reusing the storage policy already granted in
-- 0007_boiler_surveys.sql.
--
-- Safe to re-run.

alter table public.boiler_surveys add column if not exists pdf_path text;
